### ISSUE TITLE
Code Release?

### ISSUE THREAD

**Issue by kyusuncho** [xk-huang/ema#1]
Congratulations on your excellent work!

May I know when the code is available?

**Comment by xk-huang** [comment]
Hi @kyustorm7, thanks so much for your attention!
Recently I've worked intensively on both my intern project and a lab project (also about digital humans!). Thus there is limited time to clean up the code. 
Usually, I worked on it only on weekends. If everything goes smoothly, the code should be released in the middle of May!
Again, thank you! 🤗

**Comment by kyusuncho** [comment]
Hi, thanks for the heads-up. 
Will look forward to it!

**Comment by darthgera123** [comment]
hey @xk-huang sorry to bother but any updates on when you can release the code?

**Comment by xk-huang** [comment]
Hi, @darthgera123 and @kyustorm7 ! We are so sorry that EMA may need major revision before the code is released. 😢 😢 😢 
We hope the revision and code could be finished around the middle of July.

If you want to compare EMA with your work, please send us the data following the format used in [NeuralBody and Animatable-NeRF](https://github.com/zju3dv/animatable_nerf/blob/master/INSTALL.md#zju-mocap-dataset).

Deeply appreciate your attention and comments! Please stay tuned for further updates!

BR
Xiaoke

**Comment by xk-huang** [comment]
Thx for waiting! :open_hands::open_hands::open_hands:
